state_abbr: 'IL'
version: "1.0-test"
scenario: "no_growth_with_export"

solver: 'cplex'  # 'cplex','highs','gurobi'
geo_res: 'rto'  # accepts: 'rto' or 'county'
time_res: 4  # hours 
load_filter: 60e3  # MW, load above this level will be removed as outliers.
total_demand: 185e6  # Annual MWh in the first year
# total_demand: 136e6  # Annual MWh in the first year
load_growth: 0.00  # % annual growth
load_share:
  MISO-Z4: 0.33
  ComEd: 0.67

# model_years: [2025, 2030, 2035, 2040, 2045]
model_years: [2025]
plot_year: 2025

co2_limits:
  # 2020: 31.25
  # 2025: 25  # MT
  # 2030: 18.75
  # 2035: 12.5
  # 2040: 6.25
  # 2045: 0.0

# solar_years: [2016,2017,2018,2019,2020]  # NSRDB only accepts years 1998-2020
# wind_years: [2009,2010,2011,2012,2013]  # WTK only goes from 2009-2013
solar_years: [2016]  # NSRDB only accepts years 1998-2020
wind_years: [2009]  # WTK only goes from 2009-2013
load_year: 2019
fuel_cost_year: [2019]

rto_subba: ['0004','CE']  # MISO-Z4, ComEd
region_names: ['MISO-Z4','ComEd']

discount_rate: 0.07

growth_rates:  # MW/year
  Nuclear: 1e3
  Biomass: 1e3
  Natural Gas: 10e3
  Coal: 10e3
  Petroleum: 10e3
  Batteries: 5e3
  Solar: 5e3
  Wind: 5e3

# lifetime:
#   Nuclear: 80
#   Biomass: 40
#   Natural Gas: 40
#   Coal: 50
#   Solar: 20
#   Wind: 20
#   Batteries: 15
#   Petroleum: 40

lifetime:
  Nuclear: 80
  Biomass: 60
  Natural Gas: 40
  Coal: 50
  Solar: 20
  Wind: 20
  Batteries: 15
  Petroleum: 40

atb_params:
    atb_year: 2022  # the ATB publication year
    case: 'Market'  # 'R&D'
    scenario: 'Moderate'  # 'Conservative', 'Advanced'
    crp: 20  # 30
    carrier: [
      "Natural Gas",
      "Biomass",
      "Wind",
      "Solar",
      "Coal",
      "Batteries",
      "Nuclear"
    ]
    technology: [
      'CCAvgCF', 
      'CTAvgCF', 
      'Biopower', 
      'Land-Based Wind',
      'Utility PV', 
      'IGCCAvgCF', 
      'LWR',
      'NuclearSMR', 
      '10Hr Battery Storage', 
      '8Hr Battery Storage',
      '6Hr Battery Storage', 
      '4Hr Battery Storage', 
      '2Hr Battery Storage'
      ]

lines:  # this is an assumption
  v_nom: 400.
  s_nom: 0.
  x: 0.001  # reactance
  r: 0.001  # resistance
  s_nom_extendable: True

turbine_params:
  cut_in: 3.0  # m/s
  cut_out: 25.0  # m/s
  rated: 13.0  # m/s
  diameter: 103 # m
  rated_power: 2.75  # MW
  air_density: 1.225  # kg/m^3

nuclear_params:  # for existing reactors, 2023 NEI costs in context
  capacity_factor: 0.972
  capital_cost: 6.88 # $/MWh
  fixed_om: 18.68 # $/MWh
  fuel: 5.37  # $/MWh

extendable_techs:  [
      # 'CCAvgCF', 
      # 'CTAvgCF', 
      # 'IGCCAvgCF', 
      # 'Biopower', 
      # 'Land-Based Wind',
      # 'Utility PV', 
      # 'LWR',
      # 'NuclearSMR', 
      # '10Hr Battery Storage', 
      # '8Hr Battery Storage',
      # '6Hr Battery Storage', 
      # '4Hr Battery Storage', 
      # '2Hr Battery Storage'
      ]

carrier_colors:
      Natural Gas: "orange"
      Biomass: "green"
      Wind: "aqua"
      Solar: "yellow"
      Coal: "brown"
      Batteries: "grey"
      Nuclear: "magenta"
      Petroleum: "black"