state_abbr: 'IL'

geo_res: 'rto'  # accepts: 'rto' or 'county'

model_year: 2025

solar_year: 2019  # NSRDB only accepts years 1998-2020
wind_year: 2011  # WTK only goes from 2009-2013
load_year: 2019

rto_subba: ['0004','CE']  # MISO-Z4, ComEd
region_names: ['MISO-Z4','ComEd']

atb_params:
    atb_year: 2022  # the ATB publication year
    case: 'Market'  # 'R&D'
    scenario: 'Moderate'  # 'Conservative', 'Advanced'
    crp: 20  # 30
    carrier: [
      "Natural Gas",
      "Biopower",
      "Land-Based Wind",
      "Utility PV",
      "Coal",
      "Utility-Scale Battery Storage",
      "Nuclear"
    ]
    technology: [
      'CCAvgCF', 
      'CTAvgCF', 
      'Dedicated', 
      'Class1', 
      'IGCCAvgCF', 
      'Nuclear',
      'NuclearSMR', 
      '10Hr Battery Storage', 
      '8Hr Battery Storage',
      '6Hr Battery Storage', 
      '4Hr Battery Storage', 
      '2Hr Battery Storage'
      ]

lines:  # this is an assumption
  v_nom: 400.
  s_nom: 0.
  s_nom_extendable: True


turbine_params:
  cut_in: 3.0  # m/s
  cut_out: 25.0  # m/s
  rated: 13.0  # m/s
  diameter: 103 # m
  rated_power: 2.75  # MW
  air_density: 1.225  # kg/m^3