name: pypsa-illinois
channels:
    - conda-forge
    - bioconda
dependencies:
    # Requirements for core model functionality
    - python==3.10.13
    - pip
    - ipython
    - ipykernel
    
    - matplotlib
    - pandas
    - geopandas
    - numpy
    - scipy

    - jupyter
    - jupyterlab
    - seaborn
    - pypsa
    - plotly
    - pyarrow
    - iprogress
    - pyogrio
    - fiona
    - spyder-kernels=2.5
    - unyt
    - cartopy
    - descartes
    - lxml
    - snakemake
    - pycountry
    - yaml
    - geopy
    - tqdm
    - graphviz
    - networkx
    - pytz
    - camelot-py
    - pip:
      - git+https://github.com/kmax12/gridstatus.git
      - python-dotenv
      - highspy
      - nrelpy
      - us
      - census
